name: Gradle Plugins

on:
  release:
    types: [published]

permissions: {}
jobs:
  publish_plugins:
    if: ${{ github.repository == 'grace-plugins/grace-asset-pipeline' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: ['17']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Publish Gradle plugins
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: :asset-pipeline-gradle:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
